title: "Karina's website"
url: 'https://karina.io' #tThis URL is the main address for absolute links. Don't include a slash at the end.
baseurl: '' # must be "" (not "/") as "" is what GitHub pages will set.
urlimg: '/images/' # this URL points directly to the images directory, it needs a slash at the end. 
markdown: kramdown # theme works best with Kramdown (using the table of contents function)
permalink: /:categories/:title/
favicon-32x32: 'favicon.ico'
highlight: rouge # this is a code highlighter

sass:
  sass_dir: _sass
  style: :compressed

# Exclude these files from your production _site
exclude:
- .sass-cache
- Gemfile
- Gemfile.lock

# Configuration for compress.html that is used in all other layouts, see http://jch.penibelst.de for details
compress_html:
  clippings: all
  comments: [ "<!-- ", " -->" ]
  endings: all
  profile: false
  ignore:
    envs: [ development ]
