port: 4000
url: 'http://localhost:4000'
safe: true # Ensure we only use gems available to GitHub pages
sass:
  # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  style: :expanded
  line_numbers: true
