port: 4000
url: 'http://localhost:4000'
safe: true # only use gems available to GitHub pages

# overwrite sass settings in _config.yml for easy debugging, for details see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
sass:
  style: :expanded
  line_numbers: true
