port: 4000
url: 'http://localhost:4000'
safe: true # Ensure we only use gems available to GitHub pages

sass:
  # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  style: :expanded
  line_numbers: true
  # trace_selectors: true
  # debug_info: true
  # FUTURE https://github.com/jekyll/jekyll-sass-converter/issues/12
  # sourcemap: true # Produces an error

# # Description

# Beautiful layouts can be constructed using https://get.foundation/sites/docs-v5/components/grid.html

# The colors can be changed here: sass/_01_settings_colors.scss

# "Includes" can be used in two ways:
# - as templates: all includes with `_` are used for templates, like for example the `_head.html` or `_footer.html`
# - as commands: for example {% include alert success="Yay! you did it!" %} or {% include gallery %}

# To serve a pdf:
# Download PDF [here][pdf_file]{:target="_blank"}.
# [pdf_file]: /pdfs/dummy.pdf

# # Loads even on slow connection

# Perform website speed test using https://developers.google.com/speed/pagespeed/insights/ and https://www.uptrends.com/tools/website-speed-test

# Use image compressor https://imagecompressor.com/

# # GitHub Pages gems

# Here is a list of gems that GitHub pages supports: https://pages.github.com/versions/







# # Github's web hosting looks for a branch called "gh-pages"
# # Git by names the default branch "master" so we need rename
# # it to "gh-pages" so that Github can find the website files.

# # In terminal/cmd
# git checkout -b gh-pages                # Create a new branch called gh-pages
# git push origin gh-pages                # Push the gh-pages repo to github

# # On Github
# Settings (Repo settings) --> Branches --> Default Branch --> gh-pages --> Update
# (then delete the main branch)
